CREATE EXTENSION IF NOT EXISTS pgcrypto;

ALTER DATABASE taskmgr SET timezone TO 'Asia/Yekaterinburg';

create table public.users
(
    id       integer generated by default as identity constraint users_pk primary key,
    pid      integer constraint users_users_id_fk references public.users,
    ln       varchar(20),
    fn       varchar(20),
    mn       varchar(20),
    login    varchar(20) constraint users_pk2 unique,
    password varchar(100)
);

alter table public.users
    owner to taskmgr;

create table public.tasks
(
    id          integer generated by default as identity
        constraint tasks_pk
            primary key,
    title       varchar(100),
    description varchar(500),
    dt_due      timestamp,
    dt_created  timestamp default now(),
    dt_modified timestamp default now(),
    priority    integer   default 1,
    status      integer   default 0,
    owner       integer,
    assigned_to integer
);

alter table public.tasks
    owner to taskmgr;

alter table public.tasks
    add constraint tasks_users_id_fk
        foreign key (assigned_to) references public.users;

alter table public.tasks
    add constraint tasks_users_id_fk2
        foreign key (owner) references public.users;



CREATE FUNCTION check_pw(un TEXT, pass TEXT)
RETURNS BOOLEAN
language plpgsql
AS $$
DECLARE passed BOOLEAN;
BEGIN
        SELECT  (password = crypt(pass,password)) INTO passed
        FROM    users
        WHERE   login = un;

        RETURN passed;
END;
$$;

create procedure set_pw(un TEXT, pw TEXT)
language plpgsql
as $$
begin
    update users
    set password=crypt(pw,gen_salt('bf'))
    where login = un;

    commit;
end;
$$;

insert into users (id, pid, ln, fn, mn, login, password) values (1, null, 'Директор', 'И.', 'И.', 'director', null);
insert into users (id, pid, ln, fn, mn, login, password) values (2, 1, 'Заместитель1', 'И.', 'И.', 'zam1', null);
insert into users (id, pid, ln, fn, mn, login, password) values (3, 1, 'Заместитель2', 'И.', 'И.', 'zam2', null);
insert into users (id, pid, ln, fn, mn, login, password) values (4, 2, 'Сотрудник1_1', 'И.', 'И.', 'user1_1', null);
insert into users (id, pid, ln, fn, mn, login, password) values (5, 2, 'Сотрудник1_2', 'И.', 'И.', 'user1_2', null);
insert into users (id, pid, ln, fn, mn, login, password) values (6, 3, 'Сотрудник2_1', 'И.', 'И.', 'user2_1', null);
insert into users (id, pid, ln, fn, mn, login, password) values (7, 3, 'Сотрудник2_2', 'И.', 'И.', 'user2_2', null);


call set_pw('director','password');
call set_pw('zam1','password');
call set_pw('zam2','password');
call set_pw('user1_1','password');
call set_pw('user1_2','password');
call set_pw('user2_1','password');
call set_pw('user2_2','password');


INSERT INTO public.tasks (id, title, description, dt_due, dt_created, dt_modified, priority, status, owner, assigned_to) VALUES 
(DEFAULT, 'Dir Task1', 'Dir Task1', '2023-01-05 21:47:02.000000', DEFAULT, DEFAULT, 2, 0, 1, 1),
(DEFAULT, 'Dir Task2', 'Dir Task2', '2023-01-05 23:49:18.000000', DEFAULT, DEFAULT, 2, 0, 1, 1),
(DEFAULT, 'Dir Task3', 'Dir Task2', '2023-01-10 23:49:18.000000', DEFAULT, DEFAULT, 2, 0, 1, 1),
(DEFAULT, 'Dir Task4', 'Dir Task2', '2023-02-05 23:49:18.000000', DEFAULT, DEFAULT, 2, 0, 1, 1),
(DEFAULT, 'Dir Zam 1 Task1', 'Dir Zam 1 Task1', '2023-01-05 21:47:02.000000', DEFAULT, DEFAULT, 2, 0, 1, 2),
(DEFAULT, 'Dir Zam 1 Task2', 'Dir Zam 1 Task2', '2023-01-05 23:49:18.000000', DEFAULT, DEFAULT, 2, 0, 1, 2),
(DEFAULT, 'Dir Zam 1 Task3', 'Dir Zam 1 Task2', '2023-01-10 23:49:18.000000', DEFAULT, DEFAULT, 2, 0, 1, 2),
(DEFAULT, 'Dir Zam 1 Task4', 'Dir Zam 1 Task2', '2023-02-05 23:49:18.000000', DEFAULT, DEFAULT, 2, 0, 1, 2),
(DEFAULT, 'Dir Zam 2 Task1', 'Dir Zam 2 Task1', '2023-01-05 21:47:02.000000', DEFAULT, DEFAULT, 2, 0, 1, 3),
(DEFAULT, 'Dir Zam 2 Task2', 'Dir Zam 2 Task2', '2023-01-05 23:49:18.000000', DEFAULT, DEFAULT, 2, 0, 1, 3),
(DEFAULT, 'Dir Zam 2 Task3', 'Dir Zam 2 Task2', '2023-01-10 23:49:18.000000', DEFAULT, DEFAULT, 2, 0, 1, 3),
(DEFAULT, 'Dir Zam 2 Task4', 'Dir Zam 2 Task2', '2023-02-05 23:49:18.000000', DEFAULT, DEFAULT, 2, 0, 1, 3),

(DEFAULT, 'Zam 1 Task1', 'Zam 1 Task1', '2023-01-05 21:47:02.000000', DEFAULT, DEFAULT, 2, 0, 2, 2),
(DEFAULT, 'Zam 1 Task2', 'Zam 1 Task2', '2023-01-05 23:49:18.000000', DEFAULT, DEFAULT, 2, 0, 2, 2),
(DEFAULT, 'Zam 1 Task3', 'Zam 1 Task3', '2023-01-10 23:49:18.000000', DEFAULT, DEFAULT, 2, 0, 2, 2),
(DEFAULT, 'Zam 1 Task4', 'Zam 1 Task4', '2023-02-05 23:49:18.000000', DEFAULT, DEFAULT, 2, 0, 2, 2),

(DEFAULT, 'User 1_1 Zam Task1', 'User 1_1 Zam Task1', '2023-01-05 21:47:02.000000', DEFAULT, DEFAULT, 2, 0, 2, 4),
(DEFAULT, 'User 1_1 Zam Task2', 'User 1_1 Zam Task2', '2023-01-05 23:49:18.000000', DEFAULT, DEFAULT, 2, 0, 2, 4),
(DEFAULT, 'User 1_1 Zam Task3', 'User 1_1 Zam Task3', '2023-01-10 23:49:18.000000', DEFAULT, DEFAULT, 2, 0, 2, 4),
(DEFAULT, 'User 1_1 Zam Task4', 'User 1_1 Zam Task4', '2023-02-05 23:49:18.000000', DEFAULT, DEFAULT, 2, 0, 2, 4),
(DEFAULT, 'User 1_2 Zam Task1', 'User 1_2 Zam Task1', '2023-01-05 21:47:02.000000', DEFAULT, DEFAULT, 2, 0, 2, 5),
(DEFAULT, 'User 1_2 Zam Task2', 'User 1_2 Zam Task2', '2023-01-05 23:49:18.000000', DEFAULT, DEFAULT, 2, 0, 2, 5),
(DEFAULT, 'User 1_2 Zam Task3', 'User 1_2 Zam Task3', '2023-01-10 23:49:18.000000', DEFAULT, DEFAULT, 2, 0, 2, 5),
(DEFAULT, 'User 1_2 Zam Task4', 'User 1_2 Zam Task4', '2023-02-05 23:49:18.000000', DEFAULT, DEFAULT, 2, 0, 2, 5),

(DEFAULT, 'Zam 2 Task1', 'Zam 2 Task1', '2023-01-05 21:47:02.000000', DEFAULT, DEFAULT, 2, 0, 3, 3),
(DEFAULT, 'Zam 2 Task2', 'Zam 2 Task2', '2023-01-05 23:49:18.000000', DEFAULT, DEFAULT, 2, 0, 3, 3),
(DEFAULT, 'Zam 2 Task3', 'Zam 2 Task3', '2023-01-10 23:49:18.000000', DEFAULT, DEFAULT, 2, 0, 3, 3),
(DEFAULT, 'Zam 2 Task4', 'Zam 2 Task4', '2023-02-05 23:49:18.000000', DEFAULT, DEFAULT, 2, 0, 3, 3),

(DEFAULT, 'User 2_1 Zam Task1', 'User 2_1 Zam Task1', '2023-01-05 21:47:02.000000', DEFAULT, DEFAULT, 2, 0, 3, 6),
(DEFAULT, 'User 2_1 Zam Task2', 'User 2_1 Zam Task2', '2023-01-05 23:49:18.000000', DEFAULT, DEFAULT, 2, 0, 3, 6),
(DEFAULT, 'User 2_1 Zam Task3', 'User 2_1 Zam Task3', '2023-01-10 23:49:18.000000', DEFAULT, DEFAULT, 2, 0, 3, 6),
(DEFAULT, 'User 2_1 Zam Task4', 'User 2_1 Zam Task4', '2023-02-05 23:49:18.000000', DEFAULT, DEFAULT, 2, 0, 3, 6),
(DEFAULT, 'User 2_2 Zam Task1', 'User 2_2 Zam Task1', '2023-01-05 21:47:02.000000', DEFAULT, DEFAULT, 2, 0, 3, 7),
(DEFAULT, 'User 2_2 Zam Task2', 'User 2_2 Zam Task2', '2023-01-05 23:49:18.000000', DEFAULT, DEFAULT, 2, 0, 3, 7),
(DEFAULT, 'User 2_2 Zam Task3', 'User 2_2 Zam Task3', '2023-01-10 23:49:18.000000', DEFAULT, DEFAULT, 2, 0, 3, 7),
(DEFAULT, 'User 2_2 Zam Task4', 'User 2_2 Zam Task4', '2023-02-05 23:49:18.000000', DEFAULT, DEFAULT, 2, 0, 3, 7),

(DEFAULT, 'User 1_1 Task1', 'User 1_1 Task1', '2023-01-05 21:47:02.000000', DEFAULT, DEFAULT, 2, 0, 4, 4),
(DEFAULT, 'User 1_1 Task2', 'User 1_1 Task2', '2023-01-05 23:49:18.000000', DEFAULT, DEFAULT, 2, 0, 4, 4),
(DEFAULT, 'User 1_1 Task3', 'User 1_1 Task2', '2023-01-10 23:49:18.000000', DEFAULT, DEFAULT, 2, 0, 4, 4),
(DEFAULT, 'User 1_1 Task4', 'User 1_1 Task2', '2023-02-05 23:49:18.000000', DEFAULT, DEFAULT, 2, 0, 4, 4),
                              
(DEFAULT, 'User 1_2 Task1', 'User 1_2 Task1', '2023-01-05 21:47:02.000000', DEFAULT, DEFAULT, 2, 0, 5, 5),
(DEFAULT, 'User 1_2 Task2', 'User 1_2 Task2', '2023-01-05 23:49:18.000000', DEFAULT, DEFAULT, 2, 0, 5, 5),
(DEFAULT, 'User 1_2 Task3', 'User 1_2 Task2', '2023-01-10 23:49:18.000000', DEFAULT, DEFAULT, 2, 0, 5, 5),
(DEFAULT, 'User 1_2 Task4', 'User 1_2 Task2', '2023-02-05 23:49:18.000000', DEFAULT, DEFAULT, 2, 0, 5, 5),
                                                                                                        
(DEFAULT, 'User 2_1 Task1', 'User 2_1 Task1', '2023-01-05 21:47:02.000000', DEFAULT, DEFAULT, 2, 0, 6, 6),
(DEFAULT, 'User 2_1 Task2', 'User 2_1 Task2', '2023-01-05 23:49:18.000000', DEFAULT, DEFAULT, 2, 0, 6, 6),
(DEFAULT, 'User 2_1 Task3', 'User 2_1 Task2', '2023-01-10 23:49:18.000000', DEFAULT, DEFAULT, 2, 0, 6, 6),
(DEFAULT, 'User 2_1 Task4', 'User 2_1 Task2', '2023-02-05 23:49:18.000000', DEFAULT, DEFAULT, 2, 0, 6, 6),
                                                                                                        
(DEFAULT, 'User 2_2 Task1', 'User 2_2 Task1', '2023-01-05 21:47:02.000000', DEFAULT, DEFAULT, 2, 0, 7, 7),
(DEFAULT, 'User 2_2 Task2', 'User 2_2 Task2', '2023-01-05 23:49:18.000000', DEFAULT, DEFAULT, 2, 0, 7, 7),
(DEFAULT, 'User 2_2 Task3', 'User 2_2 Task2', '2023-01-10 23:49:18.000000', DEFAULT, DEFAULT, 2, 0, 7, 7),
(DEFAULT, 'User 2_2 Task4', 'User 2_2 Task2', '2023-02-05 23:49:18.000000', DEFAULT, DEFAULT, 2, 0, 7, 7);

CREATE VIEW tasks_ex as 
  select a.*, 
    b.pid mgr_id,
    b.id resp_id, 
    trim(replace(concat(b.ln, ' ', b.fn, ' ', b.mn), '  ', ' ')) resp_name, 
    case when dt_due<CURRENT_DATE + 1 then 1 when dt_due<CURRENT_DATE + 7 then 2 else 3 end cat, 
    case when dt_due<NOW() and status<2 then 1 else 0 end overdue 
  from tasks a left join users b on coalesce(assigned_to,owner)=b.id ;

CREATE VIEW users_ex as 
  select *, trim(replace(concat(ln, ' ', fn, ' ', mn), '  ', ' ')) cn from users;

